// Generated by npm run db:types from supabase/migrations. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_errors: {
        Row: {
          created_at: string;
          digest: string | null;
          id: number;
          message: string;
          method: string | null;
          path: string | null;
          route_path: string | null;
          route_type: string | null;
        };
        Insert: {
          created_at?: string;
          digest?: string | null;
          id?: number;
          message: string;
          method?: string | null;
          path?: string | null;
          route_path?: string | null;
          route_type?: string | null;
        };
        Update: {
          created_at?: string;
          digest?: string | null;
          id?: number;
          message?: string;
          method?: string | null;
          path?: string | null;
          route_path?: string | null;
          route_type?: string | null;
        };
        Relationships: [];
      };
      coach_links: {
        Row: {
          coach_id: string;
          created_at: string;
          learner_id: string;
        };
        Insert: {
          coach_id: string;
          created_at?: string;
          learner_id: string;
        };
        Update: {
          coach_id?: string;
          created_at?: string;
          learner_id?: string;
        };
        Relationships: [];
      };
      conversation_turns: {
        Row: {
          conversation_id: string;
          created_at: string;
          id: number;
          notes: Json | null;
          role: string;
          stt_provider: string | null;
          text: string;
          user_id: string;
        };
        Insert: {
          conversation_id: string;
          created_at?: string;
          id?: number;
          notes?: Json | null;
          role: string;
          stt_provider?: string | null;
          text: string;
          user_id: string;
        };
        Update: {
          conversation_id?: string;
          created_at?: string;
          id?: number;
          notes?: Json | null;
          role?: string;
          stt_provider?: string | null;
          text?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversation_turns_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      conversations: {
        Row: {
          ended_at: string | null;
          goals_done: string[];
          id: string;
          lang: string;
          level: string;
          scenario_id: string | null;
          started_at: string;
          summary: Json | null;
          user_id: string;
        };
        Insert: {
          ended_at?: string | null;
          goals_done?: string[];
          id?: string;
          lang: string;
          level: string;
          scenario_id?: string | null;
          started_at?: string;
          summary?: Json | null;
          user_id: string;
        };
        Update: {
          ended_at?: string | null;
          goals_done?: string[];
          id?: string;
          lang?: string;
          level?: string;
          scenario_id?: string | null;
          started_at?: string;
          summary?: Json | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversations_scenario_id_fkey";
            columns: ["scenario_id"];
            isOneToOne: false;
            referencedRelation: "scenarios";
            referencedColumns: ["id"];
          },
        ];
      };
      events: {
        Row: {
          app_version: string | null;
          created_at: string;
          id: number;
          path: string | null;
          props: NonNullable<Json>;
          session_id: string | null;
          type: string;
          user_id: string;
        };
        Insert: {
          app_version?: string | null;
          created_at?: string;
          id?: number;
          path?: string | null;
          props?: NonNullable<Json>;
          session_id?: string | null;
          type: string;
          user_id: string;
        };
        Update: {
          app_version?: string | null;
          created_at?: string;
          id?: number;
          path?: string | null;
          props?: NonNullable<Json>;
          session_id?: string | null;
          type?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      feedback_items: {
        Row: {
          conversation_id: string | null;
          correction: string;
          created_at: string;
          hint: string;
          id: number;
          lang: string;
          rule_key: string | null;
          rule_label: string | null;
          said: string;
          status: string;
          user_id: string;
        };
        Insert: {
          conversation_id?: string | null;
          correction: string;
          created_at?: string;
          hint: string;
          id?: number;
          lang: string;
          rule_key?: string | null;
          rule_label?: string | null;
          said: string;
          status?: string;
          user_id: string;
        };
        Update: {
          conversation_id?: string | null;
          correction?: string;
          created_at?: string;
          hint?: string;
          id?: number;
          lang?: string;
          rule_key?: string | null;
          rule_label?: string | null;
          said?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feedback_items_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      gloss_cache: {
        Row: {
          context_hash: string;
          created_at: string;
          id: number;
          lang: string;
          payload: NonNullable<Json>;
          term: string;
          ui_lang: string;
        };
        Insert: {
          context_hash: string;
          created_at?: string;
          id?: number;
          lang: string;
          payload: NonNullable<Json>;
          term: string;
          ui_lang: string;
        };
        Update: {
          context_hash?: string;
          created_at?: string;
          id?: number;
          lang?: string;
          payload?: NonNullable<Json>;
          term?: string;
          ui_lang?: string;
        };
        Relationships: [];
      };
      llm_calls: {
        Row: {
          attempt: number;
          cost_usd: number | null;
          created_at: string;
          error: string | null;
          id: number;
          input_tokens: number | null;
          latency_ms: number | null;
          model: string;
          ok: boolean;
          output_tokens: number | null;
          prompt_id: string;
          prompt_version: number;
          provider: string;
          request: Json | null;
          response: string | null;
          task: string;
          user_id: string | null;
          variant: string | null;
        };
        Insert: {
          attempt?: number;
          cost_usd?: number | null;
          created_at?: string;
          error?: string | null;
          id?: number;
          input_tokens?: number | null;
          latency_ms?: number | null;
          model: string;
          ok: boolean;
          output_tokens?: number | null;
          prompt_id: string;
          prompt_version: number;
          provider: string;
          request?: Json | null;
          response?: string | null;
          task: string;
          user_id?: string | null;
          variant?: string | null;
        };
        Update: {
          attempt?: number;
          cost_usd?: number | null;
          created_at?: string;
          error?: string | null;
          id?: number;
          input_tokens?: number | null;
          latency_ms?: number | null;
          model?: string;
          ok?: boolean;
          output_tokens?: number | null;
          prompt_id?: string;
          prompt_version?: number;
          provider?: string;
          request?: Json | null;
          response?: string | null;
          task?: string;
          user_id?: string | null;
          variant?: string | null;
        };
        Relationships: [];
      };
      model_routes: {
        Row: {
          active: boolean;
          created_at: string;
          id: number;
          model: string;
          note: string | null;
          provider: string;
          task: string;
          weight: number;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          id?: number;
          model: string;
          note?: string | null;
          provider: string;
          task: string;
          weight?: number;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          id?: number;
          model?: string;
          note?: string | null;
          provider?: string;
          task?: string;
          weight?: number;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          active_lang: string;
          created_at: string;
          display_name: string;
          levels: NonNullable<Json>;
          role: string;
          settings: NonNullable<Json>;
          ui_lang: string;
          user_id: string;
        };
        Insert: {
          active_lang?: string;
          created_at?: string;
          display_name?: string;
          levels?: NonNullable<Json>;
          role?: string;
          settings?: NonNullable<Json>;
          ui_lang?: string;
          user_id: string;
        };
        Update: {
          active_lang?: string;
          created_at?: string;
          display_name?: string;
          levels?: NonNullable<Json>;
          role?: string;
          settings?: NonNullable<Json>;
          ui_lang?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      quotes: {
        Row: {
          active: boolean;
          author: string;
          author_note: string | null;
          id: number;
          origin: string;
          source: string | null;
          status: string;
          text: string;
          text_lang: string;
          translation_ru: string;
          translation_uk: string | null;
        };
        Insert: {
          active?: boolean;
          author: string;
          author_note?: string | null;
          id?: number;
          origin?: string;
          source?: string | null;
          status: string;
          text: string;
          text_lang: string;
          translation_ru: string;
          translation_uk?: string | null;
        };
        Update: {
          active?: boolean;
          author?: string;
          author_note?: string | null;
          id?: number;
          origin?: string;
          source?: string | null;
          status?: string;
          text?: string;
          text_lang?: string;
          translation_ru?: string;
          translation_uk?: string | null;
        };
        Relationships: [];
      };
      reading_progress: {
        Row: {
          coverage: number | null;
          finished_at: string | null;
          page: number;
          text_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          coverage?: number | null;
          finished_at?: string | null;
          page?: number;
          text_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          coverage?: number | null;
          finished_at?: string | null;
          page?: number;
          text_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reading_progress_text_id_fkey";
            columns: ["text_id"];
            isOneToOne: false;
            referencedRelation: "texts";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          answer: string | null;
          auto_correct: boolean | null;
          created_at: string;
          elapsed_ms: number | null;
          id: number;
          mode: string;
          rating: number;
          state_after: Json | null;
          state_before: Json | null;
          user_id: string;
          word_id: string;
        };
        Insert: {
          answer?: string | null;
          auto_correct?: boolean | null;
          created_at?: string;
          elapsed_ms?: number | null;
          id?: number;
          mode: string;
          rating: number;
          state_after?: Json | null;
          state_before?: Json | null;
          user_id: string;
          word_id: string;
        };
        Update: {
          answer?: string | null;
          auto_correct?: boolean | null;
          created_at?: string;
          elapsed_ms?: number | null;
          id?: number;
          mode?: string;
          rating?: number;
          state_after?: Json | null;
          state_before?: Json | null;
          user_id?: string;
          word_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_word_id_fkey";
            columns: ["word_id"];
            isOneToOne: false;
            referencedRelation: "words";
            referencedColumns: ["id"];
          },
        ];
      };
      scenarios: {
        Row: {
          active: boolean;
          goals: NonNullable<Json>;
          id: string;
          lang: string;
          level: string;
          persona: string;
          setting: string;
          sort: number;
          title_ru: string;
        };
        Insert: {
          active?: boolean;
          goals: NonNullable<Json>;
          id: string;
          lang: string;
          level: string;
          persona: string;
          setting: string;
          sort?: number;
          title_ru: string;
        };
        Update: {
          active?: boolean;
          goals?: NonNullable<Json>;
          id?: string;
          lang?: string;
          level?: string;
          persona?: string;
          setting?: string;
          sort?: number;
          title_ru?: string;
        };
        Relationships: [];
      };
      speech_calls: {
        Row: {
          cached: boolean;
          cost_usd: number | null;
          created_at: string;
          error: string | null;
          id: number;
          kind: string;
          lang: string | null;
          latency_ms: number | null;
          model: string | null;
          ok: boolean;
          provider: string;
          units: number | null;
          user_id: string | null;
        };
        Insert: {
          cached?: boolean;
          cost_usd?: number | null;
          created_at?: string;
          error?: string | null;
          id?: number;
          kind: string;
          lang?: string | null;
          latency_ms?: number | null;
          model?: string | null;
          ok: boolean;
          provider: string;
          units?: number | null;
          user_id?: string | null;
        };
        Update: {
          cached?: boolean;
          cost_usd?: number | null;
          created_at?: string;
          error?: string | null;
          id?: number;
          kind?: string;
          lang?: string | null;
          latency_ms?: number | null;
          model?: string | null;
          ok?: boolean;
          provider?: string;
          units?: number | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      text_vocab: {
        Row: {
          alt: string | null;
          form: string;
          n: number;
          part_ranks: number[] | null;
          parts: string[] | null;
          rank: number | null;
          text_id: string;
        };
        Insert: {
          alt?: string | null;
          form: string;
          n: number;
          part_ranks?: number[] | null;
          parts?: string[] | null;
          rank?: number | null;
          text_id: string;
        };
        Update: {
          alt?: string | null;
          form?: string;
          n?: number;
          part_ranks?: number[] | null;
          parts?: string[] | null;
          rank?: number | null;
          text_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "text_vocab_text_id_fkey";
            columns: ["text_id"];
            isOneToOne: false;
            referencedRelation: "texts";
            referencedColumns: ["id"];
          },
        ];
      };
      texts: {
        Row: {
          active: boolean;
          author: string;
          author_note: string | null;
          availability: string;
          body: string | null;
          created_at: string;
          created_by: string | null;
          est_level: string | null;
          id: string;
          kind: string;
          lang: string;
          license: string | null;
          orthography: string;
          proper_tokens: number | null;
          source_url: string | null;
          tags: string[];
          title: string;
          token_count: number | null;
          vocab_built_at: string | null;
          word_count: number | null;
          year: string | null;
        };
        Insert: {
          active?: boolean;
          author: string;
          author_note?: string | null;
          availability?: string;
          body?: string | null;
          created_at?: string;
          created_by?: string | null;
          est_level?: string | null;
          id?: string;
          kind?: string;
          lang: string;
          license?: string | null;
          orthography?: string;
          proper_tokens?: number | null;
          source_url?: string | null;
          tags?: string[];
          title: string;
          token_count?: number | null;
          vocab_built_at?: string | null;
          word_count?: number | null;
          year?: string | null;
        };
        Update: {
          active?: boolean;
          author?: string;
          author_note?: string | null;
          availability?: string;
          body?: string | null;
          created_at?: string;
          created_by?: string | null;
          est_level?: string | null;
          id?: string;
          kind?: string;
          lang?: string;
          license?: string | null;
          orthography?: string;
          proper_tokens?: number | null;
          source_url?: string | null;
          tags?: string[];
          title?: string;
          token_count?: number | null;
          vocab_built_at?: string | null;
          word_count?: number | null;
          year?: string | null;
        };
        Relationships: [];
      };
      words: {
        Row: {
          context: string | null;
          created_at: string;
          due: string | null;
          fsrs: Json | null;
          id: string;
          kind: string;
          lang: string;
          lapses: number;
          lemma: string | null;
          note: string | null;
          reps: number;
          source: string | null;
          status: string;
          term: string;
          translation: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          context?: string | null;
          created_at?: string;
          due?: string | null;
          fsrs?: Json | null;
          id?: string;
          kind?: string;
          lang: string;
          lapses?: number;
          lemma?: string | null;
          note?: string | null;
          reps?: number;
          source?: string | null;
          status?: string;
          term: string;
          translation?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          context?: string | null;
          created_at?: string;
          due?: string | null;
          fsrs?: Json | null;
          id?: string;
          kind?: string;
          lang?: string;
          lapses?: number;
          lemma?: string | null;
          note?: string | null;
          reps?: number;
          source?: string | null;
          status?: string;
          term?: string;
          translation?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      v_daily_activity: {
        Row: {
          day: string | null;
          minutes: number | null;
          reviews: number | null;
          talk_turns: number | null;
          user_id: string | null;
          word_taps: number | null;
          words_saved: number | null;
        };
        Relationships: [];
      };
      v_model_comparison: {
        Row: {
          avg_in: number | null;
          avg_latency_ms: number | null;
          avg_out: number | null;
          calls: number | null;
          cost_usd: number | null;
          error_pct: number | null;
          model: string | null;
          p95_latency_ms: number | null;
          provider: string | null;
          task: string | null;
          variant: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      can_read_user: { Args: { target: string }; Returns: boolean };
      daily_activity: {
        Args: { p_since: string; p_user: string };
        Returns: {
          day: string;
          minutes: number;
          reviews: number;
          talk_turns: number;
          word_taps: number;
          words_saved: number;
        }[];
      };
      dearmor: { Args: { "": string }; Returns: string };
      gen_random_uuid: { Args: Record<PropertyKey, never>; Returns: string };
      gen_salt: { Args: { "": string }; Returns: string };
      is_coach: { Args: Record<PropertyKey, never>; Returns: boolean };
      pgp_armor_headers: { Args: { "": string }; Returns: Record<string, unknown>[] };
      text_fit: {
        Args: { p_band: number; p_lang: string; p_own: string[] };
        Returns: {
          known_tokens: number;
          text_id: string;
          total_tokens: number;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
