#!/usr/bin/env bash
# Generate src/lib/supabase/database.types.ts from the migrations: a throwaway Postgres in Docker,
# Supabase stand-ins + every migration, then the Supabase CLI's type generator. No project access needed.
#   npm run db:types        (after adding or changing a migration)
set -euo pipefail
cd "$(dirname "$0")/.."
NAME=sprakhylla-types-db
PORT=54329
docker rm -f "$NAME" >/dev/null 2>&1 || true
docker run -d --rm --name "$NAME" -e POSTGRES_PASSWORD=types -p "$PORT:5432" postgres:17-alpine >/dev/null
trap 'docker stop "$NAME" >/dev/null 2>&1 || true' EXIT
until docker exec "$NAME" pg_isready -U postgres -q; do sleep 0.5; done
sleep 1
for f in supabase/stubs.sql supabase/migrations/*.sql; do
  docker exec -i "$NAME" psql -q -U postgres -v ON_ERROR_STOP=1 < "$f" >/dev/null
done
OUT=src/lib/supabase/database.types.ts
npx --yes supabase@2.119.0 gen types typescript --db-url "postgresql://postgres:types@localhost:$PORT/postgres?sslmode=disable" --schema public > "$OUT.tmp"
{ echo "// Generated by npm run db:types from supabase/migrations. Do not edit by hand."; cat "$OUT.tmp"; } > "$OUT"
rm "$OUT.tmp"
npx --yes prettier@3 --log-level warn --print-width 160 --write "$OUT"
echo "Wrote $OUT"
